language: python
python:
  # - 2.6
  - 2.7
  # - 3.2
install: pip install -r requirements.txt -r test-requirements.txt
script: nosetests --with-xunit --cover-erase --with-xcoverage --cover-inclusive --cover-html --cover-package=autojenkins autojenkins
